import React from "react";
import MyBagPresenter from "./MyBagPresenter";

const MyBagContainer = ({ filterOption }) => {
  /* sample data */
  const list = [
    {
      "product_id": 1,
      "mart_name": "SEVEN11",
      "product_name": "르구르망)오레오밀크스낵30g",
      "product_image": "https://www.7-eleven.co.kr/upload/product/0000090/426278.1.jpg",
      "original_price": 2000,
      "sale_price": 1000,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 2,
      "mart_name": "CU",
      "product_name": "제니코)스모크스트링치즈24g",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8809136/850150.1.jpg",
      "original_price": 1400,
      "sale_price": 700,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 3,
      "mart_name": "EMART24",
      "product_name": "롯데푸드)요구하이145ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8801207/141228.1.jpg",
      "original_price": 1000,
      "sale_price": 500,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 4,
      "mart_name": "GS25",
      "product_name": "빙그레)닥터캡슐플레인130ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8801104/302739.1.jpg",
      "original_price": 1800,
      "sale_price": 900,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 5,
      "mart_name": "SEVEN11",
      "product_name": "프룻프룻)자몽에이드300ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8809350/885884.1.jpg",
      "original_price": 2000,
      "sale_price": 1000,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 6,
      "mart_name": "SEVEN11",
      "product_name": "프룻프룻)망고에이드300ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8809350/885877.1.jpg",
      "original_price": 2000,
      "sale_price": 1000,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 7,
      "mart_name": "SEVEN11",
      "product_name": "커피그루브)아메리카노오리지널2",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8809350/888342.1.jpg",
      "original_price": 2200,
      "sale_price": 1100,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 8,
      "mart_name": "SEVEN11",
      "product_name": "커피그루브)아메리카노마일드280",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8809350/888359.1.jpg",
      "original_price": 2200,
      "sale_price": 1100,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 9,
      "mart_name": "SEVEN11",
      "product_name": "빙그레)닥터캡슐사과130ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8801104/665421.1.jpg",
      "original_price": 1800,
      "sale_price": 900,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
    {
      "product_id": 10,
      "mart_name": "SEVEN11",
      "product_name": "남양)채움오렌지210ml",
      "product_image": "https://www.7-eleven.co.kr/upload/product/8801069/412283.1.jpg",
      "original_price": 1900,
      "sale_price": 950,
      "sale_start_day": "2021-7-1",
      "sale_end_day": "2021-7-31",
      "sale_category": "OnePlusOne",
      "gift_name": "",
      "gift_image": "",
      "gift_price": "",
      "created_day": "2021-7-5"
    },
  ];
  return <MyBagPresenter list={list} filterOption={filterOption} />;
};

export default MyBagContainer;
